### ISSUE TITLE
VC DLL errors

### ISSUE THREAD

**Issue by gointern** [fiftin/extmonswitch#1]
Hi,
When launching release exe there are two DLL errors. Which version of VC is required?

`the code execution cannot proceed because ucrtbased.dll was not found. Reinstalling the program may fix this problem.`
`The code execution cannot proceed because VCRUNTIME140D.dll was not found. Reinstalling the program may fix this problem.`

When trying to build the solution i get the following error.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4019	The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.	extmonswitch	E:\DESKTOP\PROGRAMMING\ExtMonSwitch-1.0.0\extmonswitch\extmonswitch.vcxproj	28	
`

**Comment by fiftin** [comment]
Hi @gointern 

What version of Windows do you use? I tested on Window 10 only.

**Comment by fiftin** [comment]
Please try this:

https://github.com/fiftin/ExtMonSwitch/releases/tag/v1.0.1

**Comment by gointern** [comment]
I am testing on Windows 10 machines. 21H2 10.19044.1889
It is still the same. Errors on DLLs. I tried on Windows 11 VM as well.
After DLL errors application quits.
I made a gif with v1.0.1 version.

![Video_2022-09-11_195456_0001](https://user-images.githubusercontent.com/8586023/189539911-85a0521f-0d71-4a17-9b30-307e23cbed9c.gif)

**Comment by fiftin** [comment]
Thank you.

I recompiled app with different linking options and reuploaded it. Please try this: https://github.com/fiftin/ExtMonSwitch/releases/download/v1.0.1/extmonswitch.exe

According to StackOverflow it should help :) It is very tiny app, it is not use any external libraries...

**Comment by gointern** [comment]
This version seems to work. No DLL errors and the process doesn't crash. Going to test on a laptop later on.

**Comment by fiftin** [comment]
yes, this app has no window and notify icon :) You can see in Task Manager only.

**Comment by fiftin** [comment]
I used it several years until move to MacBook :)
